services:
  chronos:
    image: chronos2:260612
    env_file: .env
    environment:
      - CUDA_VISIBLE_DEVICES=3
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    command: ./exec/keep_alive

    deploy:
      resources:
        limits:
          cpus: '30'
          memory: 80GB
        reservations:
          cpus: '30'
          memory: 80GB
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]